name: rust

on:
  workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: prints
        run: |
          echo "Hello World"
      - name: rust
        run: |
          cargo new hello-rust && cd hello-rust
          cargo check
          cargo run
